-- Migration 006: Pre-staging import, quarantine for duplicates, import job tracking
-- Run after merchant + staging schema. Idempotent (IF NOT EXISTS).

-- 1) Import job – one row per CSV upload; stores counts after process
create table if not exists public.staging_import_job (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),

  source_filename text,
  pre_staging_count int not null default 0,
  dup_count int not null default 0,
  inserted_count int not null default 0,
  status text not null default 'pending',

  constraint staging_import_job_status check (status in ('pending', 'processing', 'processed', 'failed'))
);

create index if not exists idx_staging_import_job_created_at on public.staging_import_job (created_at desc);
comment on table public.staging_import_job is 'One row per merchant DB CSV upload; dup and inserted counts after normalize/dedupe.';

-- 2) Pre-staging – same column shape as staging; rows land here on upload before process
create table if not exists public.pre_staging (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),

  import_job_id uuid references public.staging_import_job (id) on delete set null,

  "Email 1" text,
  "Email 2" text,
  "Email 3" text,
  "Email 4" text,
  "Email 5" text,
  "Email 6" text,
  "Owner 2 Email 1" text,
  "Owner 2 Email 2" text,
  "Owner 2 Email 3" text,
  "Owner 2 Email 4" text,
  "Owner 2 Email 5" text,
  "First Name" text,
  "Last Name" text,
  "Phone 1" text,
  "Business Name" text,
  "Business Start Date" text,
  "EIN" text,
  "Address Street" text,
  "City" text,
  "State" text,
  "ZIP" text,
  "Business Type" text,
  "Monthly Revenue" text,
  "Home Address" text,
  "City 2" text,
  "State 2" text,
  "ZIP 2" text
);

create index if not exists idx_pre_staging_import_job on public.pre_staging (import_job_id);
create index if not exists idx_pre_staging_email_1 on public.pre_staging ("Email 1");
comment on table public.pre_staging is 'Landing table for purchased merchant DB CSV uploads; process moves new rows to staging, dupes to staging_quarantine.';

-- 3) Quarantine – duplicates from pre_staging that already exist in staging (by email match)
create table if not exists public.staging_quarantine (
  id bigint generated by default as identity primary key,
  quarantined_at timestamptz not null default now(),

  import_job_id uuid references public.staging_import_job (id) on delete set null,
  quarantine_reason text not null default 'duplicate',
  original_staging_id bigint references public.staging (id) on delete set null,

  "Email 1" text,
  "Email 2" text,
  "Email 3" text,
  "Email 4" text,
  "Email 5" text,
  "Email 6" text,
  "Owner 2 Email 1" text,
  "Owner 2 Email 2" text,
  "Owner 2 Email 3" text,
  "Owner 2 Email 4" text,
  "Owner 2 Email 5" text,
  "First Name" text,
  "Last Name" text,
  "Phone 1" text,
  "Business Name" text,
  "Business Start Date" text,
  "EIN" text,
  "Address Street" text,
  "City" text,
  "State" text,
  "ZIP" text,
  "Business Type" text,
  "Monthly Revenue" text,
  "Home Address" text,
  "City 2" text,
  "State 2" text,
  "ZIP 2" text
);

create index if not exists idx_staging_quarantine_import_job on public.staging_quarantine (import_job_id);
create index if not exists idx_staging_quarantine_reason on public.staging_quarantine (quarantine_reason);
comment on table public.staging_quarantine is 'Rows from pre_staging that matched existing staging (by email); kept for audit, not used in outreach.';
