-- =============================================================================
-- Staging contact activity – track outreach and nudge activity per contact
-- Supabase project: Merchant DB
-- Run this in the Merchant DB project → SQL Editor, in one go.
-- Requires: public.application_sessions (run supabase-application-sessions.sql first if missing).
-- Creates public.staging below if it does not exist.
-- =============================================================================

-- Ensure public.staging exists (creates it if you haven't run supabase-staging.sql yet).
create table if not exists public.staging (
  id bigint generated by default as identity primary key,
  "Email 1" text,
  "Email 2" text,
  "Email 3" text,
  "Email 4" text,
  "Email 5" text,
  "Email 6" text,
  "Owner 2 Email 1" text,
  "Owner 2 Email 2" text,
  "Owner 2 Email 3" text,
  "Owner 2 Email 4" text,
  "Owner 2 Email 5" text,
  "First Name" text,
  "Last Name" text,
  "Phone 1" text,
  "Business Name" text,
  "Business Start Date" text,
  "EIN" text,
  "Address Street" text,
  "City" text,
  "State" text,
  "ZIP" text,
  "Business Type" text,
  "Monthly Revenue" text,
  "Home Address" text,
  "City 2" text,
  "State 2" text,
  "ZIP 2" text,
  created_at timestamptz default now()
);
create index if not exists idx_staging_email_1 on public.staging ("Email 1");

-- One row per contact event. email = normalized (lowercase, trimmed).
-- activity_type: 'outreach' (your cold email/campaign), 'nudge_30m', 'nudge_24h',
--   'nudge_15d', 'application_started', 'application_submitted'.
-- Insert 'outreach' when you send a campaign; app can insert nudge types when sending.
create table if not exists public.contact_activity (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),

  email text not null,
  activity_type text not null,
  occurred_at timestamptz not null default now(),
  staging_id bigint references public.staging(id) on delete set null,
  metadata jsonb,

  constraint contact_activity_type check (
    activity_type in (
      'outreach',
      'nudge_30m',
      'nudge_24h',
      'nudge_15d',
      'application_started',
      'application_submitted'
    )
  )
);

create index if not exists idx_contact_activity_email on public.contact_activity (lower(trim(email)));
create index if not exists idx_contact_activity_email_type on public.contact_activity (lower(trim(email)), activity_type);
create index if not exists idx_contact_activity_staging_id on public.contact_activity (staging_id);
create index if not exists idx_contact_activity_occurred_at on public.contact_activity (occurred_at desc);

comment on table public.contact_activity is 'Tracks each contact touch: outreach (your lists), nudges (cron), application events. Use to filter staging for new outreach.';

-- Drop views that depend on normalize_email, then drop/recreate the function (so param name can change).
drop view if exists public.staging_available_for_outreach;
drop view if exists public.staging_not_contacted;
drop function if exists public.normalize_email(text);

create or replace function public.normalize_email(e text)
returns text
language sql
immutable
as $$
  select lower(trim(nullif(trim(coalesce(e, '')), '')));
$$;

-- Staging rows that have NOT had any outreach on any of their emails.
-- Use this to build lists of "never contacted" for cold outreach.
create or replace view public.staging_not_contacted as
select s.*
from public.staging s
where not exists (
  select 1 from public.contact_activity ca
  where ca.activity_type = 'outreach'
  and (
    (s."Email 1" is not null and public.normalize_email(s."Email 1") <> '' and ca.email = public.normalize_email(s."Email 1"))
    or (s."Email 2" is not null and public.normalize_email(s."Email 2") <> '' and ca.email = public.normalize_email(s."Email 2"))
    or (s."Email 3" is not null and public.normalize_email(s."Email 3") <> '' and ca.email = public.normalize_email(s."Email 3"))
    or (s."Email 4" is not null and public.normalize_email(s."Email 4") <> '' and ca.email = public.normalize_email(s."Email 4"))
    or (s."Email 5" is not null and public.normalize_email(s."Email 5") <> '' and ca.email = public.normalize_email(s."Email 5"))
    or (s."Email 6" is not null and public.normalize_email(s."Email 6") <> '' and ca.email = public.normalize_email(s."Email 6"))
    or (s."Owner 2 Email 1" is not null and public.normalize_email(s."Owner 2 Email 1") <> '' and ca.email = public.normalize_email(s."Owner 2 Email 1"))
    or (s."Owner 2 Email 2" is not null and public.normalize_email(s."Owner 2 Email 2") <> '' and ca.email = public.normalize_email(s."Owner 2 Email 2"))
    or (s."Owner 2 Email 3" is not null and public.normalize_email(s."Owner 2 Email 3") <> '' and ca.email = public.normalize_email(s."Owner 2 Email 3"))
    or (s."Owner 2 Email 4" is not null and public.normalize_email(s."Owner 2 Email 4") <> '' and ca.email = public.normalize_email(s."Owner 2 Email 4"))
    or (s."Owner 2 Email 5" is not null and public.normalize_email(s."Owner 2 Email 5") <> '' and ca.email = public.normalize_email(s."Owner 2 Email 5"))
  )
);

comment on view public.staging_not_contacted is 'Staging rows where no email in the row has activity_type = outreach. Use for new outreach lists.';

-- Staging rows that are both (1) not contacted and (2) not in application_sessions
-- (so cron is not already nudging them). Use to avoid double-touching.
create or replace view public.staging_available_for_outreach as
select s.*
from public.staging s
where not exists (
  select 1 from public.contact_activity ca
  where ca.activity_type = 'outreach'
  and (
    (s."Email 1" is not null and public.normalize_email(s."Email 1") <> '' and ca.email = public.normalize_email(s."Email 1"))
    or (s."Email 2" is not null and public.normalize_email(s."Email 2") <> '' and ca.email = public.normalize_email(s."Email 2"))
    or (s."Email 3" is not null and public.normalize_email(s."Email 3") <> '' and ca.email = public.normalize_email(s."Email 3"))
    or (s."Email 4" is not null and public.normalize_email(s."Email 4") <> '' and ca.email = public.normalize_email(s."Email 4"))
    or (s."Email 5" is not null and public.normalize_email(s."Email 5") <> '' and ca.email = public.normalize_email(s."Email 5"))
    or (s."Email 6" is not null and public.normalize_email(s."Email 6") <> '' and ca.email = public.normalize_email(s."Email 6"))
    or (s."Owner 2 Email 1" is not null and public.normalize_email(s."Owner 2 Email 1") <> '' and ca.email = public.normalize_email(s."Owner 2 Email 1"))
    or (s."Owner 2 Email 2" is not null and public.normalize_email(s."Owner 2 Email 2") <> '' and ca.email = public.normalize_email(s."Owner 2 Email 2"))
    or (s."Owner 2 Email 3" is not null and public.normalize_email(s."Owner 2 Email 3") <> '' and ca.email = public.normalize_email(s."Owner 2 Email 3"))
    or (s."Owner 2 Email 4" is not null and public.normalize_email(s."Owner 2 Email 4") <> '' and ca.email = public.normalize_email(s."Owner 2 Email 4"))
    or (s."Owner 2 Email 5" is not null and public.normalize_email(s."Owner 2 Email 5") <> '' and ca.email = public.normalize_email(s."Owner 2 Email 5"))
  )
)
and not exists (
  select 1 from public.application_sessions a
  where (
    (s."Email 1" is not null and public.normalize_email(s."Email 1") <> '' and a.email = public.normalize_email(s."Email 1"))
    or (s."Email 2" is not null and public.normalize_email(s."Email 2") <> '' and a.email = public.normalize_email(s."Email 2"))
    or (s."Email 3" is not null and public.normalize_email(s."Email 3") <> '' and a.email = public.normalize_email(s."Email 3"))
    or (s."Email 4" is not null and public.normalize_email(s."Email 4") <> '' and a.email = public.normalize_email(s."Email 4"))
    or (s."Email 5" is not null and public.normalize_email(s."Email 5") <> '' and a.email = public.normalize_email(s."Email 5"))
    or (s."Email 6" is not null and public.normalize_email(s."Email 6") <> '' and a.email = public.normalize_email(s."Email 6"))
    or (s."Owner 2 Email 1" is not null and public.normalize_email(s."Owner 2 Email 1") <> '' and a.email = public.normalize_email(s."Owner 2 Email 1"))
    or (s."Owner 2 Email 2" is not null and public.normalize_email(s."Owner 2 Email 2") <> '' and a.email = public.normalize_email(s."Owner 2 Email 2"))
    or (s."Owner 2 Email 3" is not null and public.normalize_email(s."Owner 2 Email 3") <> '' and a.email = public.normalize_email(s."Owner 2 Email 3"))
    or (s."Owner 2 Email 4" is not null and public.normalize_email(s."Owner 2 Email 4") <> '' and a.email = public.normalize_email(s."Owner 2 Email 4"))
    or (s."Owner 2 Email 5" is not null and public.normalize_email(s."Owner 2 Email 5") <> '' and a.email = public.normalize_email(s."Owner 2 Email 5"))
  )
);

comment on view public.staging_available_for_outreach is 'Staging rows not yet contacted AND not in application_sessions (cron not nudging). Safe for new outreach.';

-- Optional: when you send outreach, insert one row per contact so they drop out of the views above.
-- Example (run from your app or SQL after sending a campaign):
--   insert into public.contact_activity (email, activity_type, staging_id)
--   values (lower(trim('lead@example.com')), 'outreach', 12345);
-- Use staging_id if you know the staging row; otherwise leave null.
