-- Supabase Storage Policies for merchant-documents bucket
-- This file documents the required RLS policies and CORS configuration

-- ============================================================================
-- STORAGE BUCKET SETUP
-- ============================================================================
-- Bucket name: merchant-documents
-- Public: false (files are private by default)
-- Allowed MIME types: application/pdf, image/jpeg, image/jpg, image/gif, text/csv
-- File size limit: 5GB (Supabase default for standard uploads)

-- ============================================================================
-- RLS POLICIES
-- ============================================================================

-- Policy 1: Allow authenticated uploads (for presigned URLs)
-- This policy allows uploads using presigned URLs generated by the server
CREATE POLICY "Allow presigned uploads"
ON storage.objects FOR INSERT
TO authenticated
WITH CHECK (bucket_id = 'merchant-documents');

-- Policy 2: Allow public uploads (alternative if using anon key)
-- Use this if your client-side uploads use the anon key instead of authenticated
CREATE POLICY "Allow public uploads"
ON storage.objects FOR INSERT
TO anon
WITH CHECK (bucket_id = 'merchant-documents');

-- Policy 3: Allow service role to read/write (for server operations)
CREATE POLICY "Allow service role full access"
ON storage.objects
TO service_role
USING (bucket_id = 'merchant-documents')
WITH CHECK (bucket_id = 'merchant-documents');

-- Policy 4: Allow service role to delete (for cleanup operations)
CREATE POLICY "Allow service role delete"
ON storage.objects FOR DELETE
TO service_role
USING (bucket_id = 'merchant-documents');

-- Policy 5: Allow moving files (for finalizing uploads)
-- This enables the server to move files from temp/ to final location
CREATE POLICY "Allow service role update"
ON storage.objects FOR UPDATE
TO service_role
USING (bucket_id = 'merchant-documents')
WITH CHECK (bucket_id = 'merchant-documents');

-- ============================================================================
-- CORS CONFIGURATION
-- ============================================================================
-- To enable direct browser uploads to Supabase storage, configure CORS in:
-- Supabase Dashboard → Storage → Configuration → CORS

-- Recommended CORS settings:
-- Allowed Origins: 
--   - http://localhost:3000 (development)
--   - http://localhost:3001 (development - alternative port)
--   - https://yourdomain.com (production)
--   - https://www.yourdomain.com (production with www)
--
-- Allowed Methods: GET, POST, PUT, DELETE
-- Allowed Headers: authorization, x-client-info, apikey, content-type
-- Max Age: 3600

-- ============================================================================
-- ENVIRONMENT VARIABLES REQUIRED
-- ============================================================================
-- On the client side (browser):
--   NEXT_PUBLIC_SUPABASE_URL=https://your-project.supabase.co
--   NEXT_PUBLIC_SUPABASE_ANON_KEY=your-anon-key
--
-- On the server side (server actions):
--   NEXT_PUBLIC_SUPABASE_URL=https://your-project.supabase.co
--   SUPABASE_SERVICE_ROLE_KEY=your-service-role-key

-- ============================================================================
-- SECURITY CONSIDERATIONS
-- ============================================================================
-- 1. Presigned URLs expire after 2 hours (Supabase default)
-- 2. Files are stored in temp/ initially, then moved to final location on submission
-- 3. Orphaned files in temp/ should be cleaned up periodically (see cleanup-uploads.ts)
-- 4. Service role key should NEVER be exposed to the client
-- 5. RLS policies ensure users can only upload, not download without auth

-- ============================================================================
-- BUCKET CREATION (if not exists)
-- ============================================================================
-- Run this in Supabase SQL Editor if bucket doesn't exist:

INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'merchant-documents',
  'merchant-documents',
  false,
  5368709120, -- 5GB in bytes
  ARRAY['application/pdf', 'image/jpeg', 'image/jpg', 'image/gif', 'text/csv']
)
ON CONFLICT (id) DO NOTHING;

-- ============================================================================
-- TESTING
-- ============================================================================
-- 1. Test presigned URL generation:
--    - Call createUploadUrl from a client component
--    - Verify it returns a valid token and path
--
-- 2. Test file upload:
--    - Upload a small file (<1MB) to verify basic functionality
--    - Upload a large file (>10MB) to verify large file support
--    - Upload a file >4.5MB to verify it bypasses Vercel limit
--
-- 3. Test file cleanup:
--    - Upload a file, then delete it before submission
--    - Verify file is removed from storage
--
-- 4. Test file finalization:
--    - Upload files and submit the form
--    - Verify files are moved from temp/ to final applicationId path
--    - Verify files appear in email attachments

-- ============================================================================
-- MONITORING & MAINTENANCE
-- ============================================================================
-- Periodically clean up temp/ files older than 24 hours:
-- (This can be set up as a Supabase Edge Function or cron job)

-- SELECT storage.delete_object('merchant-documents', name)
-- FROM storage.objects
-- WHERE bucket_id = 'merchant-documents'
--   AND name LIKE 'temp/%'
--   AND created_at < NOW() - INTERVAL '24 hours';
