-- =============================================================================
-- Deploy: Merchant DB – run once in Merchant DB → SQL Editor
-- OneDayCap website only. Do not use for WatermarkFile project.
-- Idempotent: safe to run multiple times (creates if not exists / replace).
-- =============================================================================

-- 1) Trigger helper (required by application_sessions). Skip if you already have merchant_applications.
create or replace function public.set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

-- 2) Application sessions – abandonment nudges, resume links, 15-day follow-up
create table if not exists public.application_sessions (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  email text not null,
  token text not null,
  current_step smallint not null default 1 check (current_step >= 1 and current_step <= 5),
  last_event text,
  last_event_at timestamptz,
  started_at timestamptz not null default now(),

  submitted_at timestamptz,
  nudge_30m_sent_at timestamptz,
  nudge_24h_sent_at timestamptz,
  last_15d_followup_sent_at timestamptz,

  opted_out boolean not null default false,

  utm_source text,
  campaign_id text,

  unique (token),
  unique (email)
);

create index if not exists idx_application_sessions_email on public.application_sessions (email);
create index if not exists idx_application_sessions_token on public.application_sessions (token);
create index if not exists idx_application_sessions_last_event_at on public.application_sessions (last_event_at);
create index if not exists idx_application_sessions_nudges on public.application_sessions (submitted_at, opted_out, nudge_30m_sent_at, nudge_24h_sent_at, last_event_at, started_at);

drop trigger if exists set_application_sessions_updated_at on public.application_sessions;
create trigger set_application_sessions_updated_at
  before update on public.application_sessions
  for each row execute function public.set_updated_at();

alter table public.application_sessions enable row level security;

comment on table public.application_sessions is 'Tracks application funnel for abandonment nudges (30m, 24h), 15-day follow-up, and resume links.';

-- 3) Staging (if not exists) – for form prefill and contact-activity views
create table if not exists public.staging (
  id bigint generated by default as identity primary key,
  "Email 1" text,
  "Email 2" text,
  "Email 3" text,
  "Email 4" text,
  "Email 5" text,
  "Email 6" text,
  "Owner 2 Email 1" text,
  "Owner 2 Email 2" text,
  "Owner 2 Email 3" text,
  "Owner 2 Email 4" text,
  "Owner 2 Email 5" text,
  "First Name" text,
  "Last Name" text,
  "Phone 1" text,
  "Business Name" text,
  "Business Start Date" text,
  "EIN" text,
  "Address Street" text,
  "City" text,
  "State" text,
  "ZIP" text,
  "Business Type" text,
  "Monthly Revenue" text,
  "Home Address" text,
  "City 2" text,
  "State 2" text,
  "ZIP 2" text,
  created_at timestamptz default now()
);

create index if not exists idx_staging_email_1 on public.staging ("Email 1");

-- 4) Contact activity – track outreach and nudge per contact
create table if not exists public.contact_activity (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),

  email text not null,
  activity_type text not null,
  occurred_at timestamptz not null default now(),
  staging_id bigint references public.staging(id) on delete set null,
  metadata jsonb,

  constraint contact_activity_type check (
    activity_type in (
      'outreach',
      'nudge_30m',
      'nudge_24h',
      'nudge_15d',
      'application_started',
      'application_submitted'
    )
  )
);

create index if not exists idx_contact_activity_email on public.contact_activity (lower(trim(email)));
create index if not exists idx_contact_activity_email_type on public.contact_activity (lower(trim(email)), activity_type);
create index if not exists idx_contact_activity_staging_id on public.contact_activity (staging_id);
create index if not exists idx_contact_activity_occurred_at on public.contact_activity (occurred_at desc);

comment on table public.contact_activity is 'Tracks each contact touch: outreach (your lists), nudges (cron), application events. Use to filter staging for new outreach.';

-- 5) Helper for email matching. Drop dependent views first, then function (so param name can change).
drop view if exists public.staging_available_for_outreach;
drop view if exists public.staging_not_contacted;
drop function if exists public.normalize_email(text);

create or replace function public.normalize_email(e text)
returns text
language sql
immutable
as $$
  select lower(trim(nullif(trim(coalesce(e, '')), '')));
$$;

-- 6) Views – staging not contacted / available for outreach
create or replace view public.staging_not_contacted as
select s.*
from public.staging s
where not exists (
  select 1 from public.contact_activity ca
  where ca.activity_type = 'outreach'
  and (
    (s."Email 1" is not null and public.normalize_email(s."Email 1") <> '' and ca.email = public.normalize_email(s."Email 1"))
    or (s."Email 2" is not null and public.normalize_email(s."Email 2") <> '' and ca.email = public.normalize_email(s."Email 2"))
    or (s."Email 3" is not null and public.normalize_email(s."Email 3") <> '' and ca.email = public.normalize_email(s."Email 3"))
    or (s."Email 4" is not null and public.normalize_email(s."Email 4") <> '' and ca.email = public.normalize_email(s."Email 4"))
    or (s."Email 5" is not null and public.normalize_email(s."Email 5") <> '' and ca.email = public.normalize_email(s."Email 5"))
    or (s."Email 6" is not null and public.normalize_email(s."Email 6") <> '' and ca.email = public.normalize_email(s."Email 6"))
    or (s."Owner 2 Email 1" is not null and public.normalize_email(s."Owner 2 Email 1") <> '' and ca.email = public.normalize_email(s."Owner 2 Email 1"))
    or (s."Owner 2 Email 2" is not null and public.normalize_email(s."Owner 2 Email 2") <> '' and ca.email = public.normalize_email(s."Owner 2 Email 2"))
    or (s."Owner 2 Email 3" is not null and public.normalize_email(s."Owner 2 Email 3") <> '' and ca.email = public.normalize_email(s."Owner 2 Email 3"))
    or (s."Owner 2 Email 4" is not null and public.normalize_email(s."Owner 2 Email 4") <> '' and ca.email = public.normalize_email(s."Owner 2 Email 4"))
    or (s."Owner 2 Email 5" is not null and public.normalize_email(s."Owner 2 Email 5") <> '' and ca.email = public.normalize_email(s."Owner 2 Email 5"))
  )
);

comment on view public.staging_not_contacted is 'Staging rows where no email has activity_type = outreach. Use for new outreach lists.';

create or replace view public.staging_available_for_outreach as
select s.*
from public.staging s
where not exists (
  select 1 from public.contact_activity ca
  where ca.activity_type = 'outreach'
  and (
    (s."Email 1" is not null and public.normalize_email(s."Email 1") <> '' and ca.email = public.normalize_email(s."Email 1"))
    or (s."Email 2" is not null and public.normalize_email(s."Email 2") <> '' and ca.email = public.normalize_email(s."Email 2"))
    or (s."Email 3" is not null and public.normalize_email(s."Email 3") <> '' and ca.email = public.normalize_email(s."Email 3"))
    or (s."Email 4" is not null and public.normalize_email(s."Email 4") <> '' and ca.email = public.normalize_email(s."Email 4"))
    or (s."Email 5" is not null and public.normalize_email(s."Email 5") <> '' and ca.email = public.normalize_email(s."Email 5"))
    or (s."Email 6" is not null and public.normalize_email(s."Email 6") <> '' and ca.email = public.normalize_email(s."Email 6"))
    or (s."Owner 2 Email 1" is not null and public.normalize_email(s."Owner 2 Email 1") <> '' and ca.email = public.normalize_email(s."Owner 2 Email 1"))
    or (s."Owner 2 Email 2" is not null and public.normalize_email(s."Owner 2 Email 2") <> '' and ca.email = public.normalize_email(s."Owner 2 Email 2"))
    or (s."Owner 2 Email 3" is not null and public.normalize_email(s."Owner 2 Email 3") <> '' and ca.email = public.normalize_email(s."Owner 2 Email 3"))
    or (s."Owner 2 Email 4" is not null and public.normalize_email(s."Owner 2 Email 4") <> '' and ca.email = public.normalize_email(s."Owner 2 Email 4"))
    or (s."Owner 2 Email 5" is not null and public.normalize_email(s."Owner 2 Email 5") <> '' and ca.email = public.normalize_email(s."Owner 2 Email 5"))
  )
)
and not exists (
  select 1 from public.application_sessions a
  where (
    (s."Email 1" is not null and public.normalize_email(s."Email 1") <> '' and a.email = public.normalize_email(s."Email 1"))
    or (s."Email 2" is not null and public.normalize_email(s."Email 2") <> '' and a.email = public.normalize_email(s."Email 2"))
    or (s."Email 3" is not null and public.normalize_email(s."Email 3") <> '' and a.email = public.normalize_email(s."Email 3"))
    or (s."Email 4" is not null and public.normalize_email(s."Email 4") <> '' and a.email = public.normalize_email(s."Email 4"))
    or (s."Email 5" is not null and public.normalize_email(s."Email 5") <> '' and a.email = public.normalize_email(s."Email 5"))
    or (s."Email 6" is not null and public.normalize_email(s."Email 6") <> '' and a.email = public.normalize_email(s."Email 6"))
    or (s."Owner 2 Email 1" is not null and public.normalize_email(s."Owner 2 Email 1") <> '' and a.email = public.normalize_email(s."Owner 2 Email 1"))
    or (s."Owner 2 Email 2" is not null and public.normalize_email(s."Owner 2 Email 2") <> '' and a.email = public.normalize_email(s."Owner 2 Email 2"))
    or (s."Owner 2 Email 3" is not null and public.normalize_email(s."Owner 2 Email 3") <> '' and a.email = public.normalize_email(s."Owner 2 Email 3"))
    or (s."Owner 2 Email 4" is not null and public.normalize_email(s."Owner 2 Email 4") <> '' and a.email = public.normalize_email(s."Owner 2 Email 4"))
    or (s."Owner 2 Email 5" is not null and public.normalize_email(s."Owner 2 Email 5") <> '' and a.email = public.normalize_email(s."Owner 2 Email 5"))
  )
);

comment on view public.staging_available_for_outreach is 'Staging rows not yet contacted AND not in application_sessions (cron not nudging). Safe for new outreach.';
