-- =============================================================================
-- Staging table – for application form lookup-by-email prefill
-- Supabase project: Merchant DB
-- Run this in Merchant DB → SQL Editor if you need to create the table.
-- The app matches user email against Email 1–6 and Owner 2 Email 1–5, then
-- prefills the form from the columns listed below.
-- =============================================================================

-- Use lowercase name so the default STAGING_TABLE (staging) finds it.
-- Column names are quoted so spaces and case are preserved (e.g. "Email 1").
create table if not exists public.staging (
  id bigint generated by default as identity primary key,

  -- Email columns (lookup tries these in order)
  "Email 1" text,
  "Email 2" text,
  "Email 3" text,
  "Email 4" text,
  "Email 5" text,
  "Email 6" text,
  "Owner 2 Email 1" text,
  "Owner 2 Email 2" text,
  "Owner 2 Email 3" text,
  "Owner 2 Email 4" text,
  "Owner 2 Email 5" text,

  -- Personal (form: First Name, Last Name, Phone 1)
  "First Name" text,
  "Last Name" text,
  "Phone 1" text,

  -- Business (form: Business Name, Start Date, EIN, Address, City, State, ZIP, Business Type)
  "Business Name" text,
  "Business Start Date" text,
  "EIN" text,
  "Address Street" text,
  "City" text,
  "State" text,
  "ZIP" text,
  "Business Type" text,

  -- Financial (form: Monthly Revenue)
  "Monthly Revenue" text,

  -- Credit / ownership address (form: Home Address, City 2, State 2, ZIP 2)
  "Home Address" text,
  "City 2" text,
  "State 2" text,
  "ZIP 2" text,

  created_at timestamptz default now()
);

-- Optional: index for email lookups (speeds up ilike on Email 1)
create index if not exists idx_staging_email_1 on public.staging ("Email 1");

comment on table public.staging is 'Merchant staging data for application form lookup-by-email prefill';
